---
# handlers file for mightydok-bareos-dir

-   name: restart bareos-dir
    service:
        name: bareos-dir
        state: restarted

-   name: restart apache2
    service:
        name: apache2
        state: restarted

-   name: reload bareos-dir
    shell: echo "reload" | /usr/sbin/bconsole
